# Application Info
info:
  name: ${project.artifactId}
  description: ${project.description}
  version: ${project.version}

server:
  port: 8501
  context-path: /${project.artifactId}

endpoints:
  enabled: false
  sensitive: true
  configprops.enabled: true
  info.enabled: true
  health.enabled: true
  metrics.enabled: true

container:
  url: http://localhost:8500/geometry-container-ws/